### ISSUE TITLE
Cannot install because of PTY.js issue

### ISSUE THREAD

**Issue by andylouisqin** [petethepig/devtools-terminal#41]
Below is the error message I'm receiving when I try to run the command: "sudo npm install -g devtools-terminal":

npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js

**Comment by matianyun** [comment]
Thanks very much!

**Comment by joeithub** [comment]
make: Entering directory '/usr/lib/node_modules/devtools-terminal/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: g++: No such file or directory
make: *** [pty.target.mk:107: Release/obj.target/pty/src/unix/pty.o] Error 127
make: Leaving directory '/usr/lib/node_modules/devtools-terminal/node_modules/pty.js/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.43-1-lts
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/devtools-terminal/node_modules/pty.js
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.c9/tmp/.npm/_logs/2020-07-20T15_56_12_501Z-debug.log
