### ISSUE TITLE
Does not work in OSX

### ISSUE THREAD

**Issue by msanand** [petethepig/devtools-terminal#57]
Hi,

'devtools-terminal' worked perfectly fine until the move to Native Messaging API. Since then, I've never been able to get it working. I've installed and re-installed everything following the instructions, but all I see when I open terminal is the announcement and instructions to install it.
I really loved having devtools-terminal as it greatly enhanced my dev productivity. Please let me know if I'm missing something or how I can get it working again.

Thanks,
Anand

**Comment by fungl164** [comment]
This works on Yosemite + Chrome - Version 39.0.2171.95 ( see http://stackoverflow.com/a/24981514 )
> $ mkdir /tmp/pty.js
> $ git clone https://github.com/chjj/pty.js.git /tmp/pty.js
> $ vi /tmp/pty.js/src/unix/pty.cc

replace line 39: #include <util.h> with #include "/usr/include/util.h"
> $ npm install -g /tmp/pty.js
> $ npm install -g devtools-terminal
> $ sudo devtools-terminal --install --id=leakmhneaibbdapdoienlkifomjceknl

**Comment by msanand** [comment]
Thanks for the details, @fungl164 . I tried following the instructions, but I get an error when installing '/tmp/pty.js' from the local directory. Any ideas how I can fix this?

Error details:
npm ERR! addLocal Could not install /tmp/tpy.js
npm ERR! Error: ENOENT, stat '/tmp/tpy.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.4.0
npm ERR! cwd /private/tmp/pty.js
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /tmp/tpy.js
npm ERR! code ENOENT
npm ERR! errno 34

**Comment by fungl164** [comment]
@msanand I just noticed something peculiar in <code>/tmp/tpy.js</code> vs <code>/tmp/pty.js</code>.  

I suspect it's a simple typo on the command.  Give this a try <code>npm install -g /tmp/pty.js</code>

**Comment by brschwar** [comment]
I am using OSX: 10.10.1, Chrome: 40.0.2214.91, Node: 0.10.35

I am able to install devtools terminal. Note: pty.js now seems to be pointing to the correct path:
https://github.com/chjj/pty.js/commit/61acd15285458528d61838b9c4145a48571c041b

I can run devtools-terminal after installing globally and adding the ID (which now gives me a "Chrome Native Messaging host application installed successfully"):
$ devtools-terminal
   info  - socket.io started

However, I still see the welcome screen with the Native Messaging API messaging instead of a prompt. Is anyone else still getting that Announcement screen?

**Comment by tonyjessup** [comment]
thx @fungl164 this totally fixed the install. works great running chrome 40.0 on osx 10.10.1

**Comment by brschwar** [comment]
Got this to work, finally. I assume there may have been an issue accessing the tool's default 8080 port from the browser to the socket server. I'll keep an eye on it, but otherwise, the plugin works like a charm.

**Comment by DannyMoerkerke** [comment]
I followed @msanand's steps but unfortunately it's still not working for me on OSX 10.10.2, Chrome  41.0.2272.101.
I remember I had it working before but I recently switched to io.js, installed with NVM. Could that be an issue?

**Comment by Devric** [comment]
my devtool-terminal server is up, and it seems like it can establish an io handshake every time i try to connect

      http://localhost:8080     admin    

it will than create a new auth id

       info  - handshake authorized sSgiOUPtbrvttxIH4C4I 




but the chrome terminal just says connection failed

**Comment by chadbailey59** [comment]
Having the same problem. @brschwar , did you do anything special to get it to work?

**Comment by brschwar** [comment]
@chadbailey59 

I was able to get it working following the directions on this blog:
    http://blog.dfilimonov.com/2013/09/12/devtools-terminal.html

Please note that you will need to install devtools-terminal globally:
```
 sudo npm install -g devtools-terminal
```
Then run `devtools-terminal` which kicks off a socket.io connection. 

Next, access the terminal tab from the developer tools and ignore the NPAPI announcement. That's what got me at first - that announcement doesn't go away, instead click on the '...' preferences menu and login to a Remote Connection with the credentials: `http://localhost:8080` with a password of `admin`. 

That worked for me - I could then use that panel in the same manner as I was able to before the Native Messaging update. Possible issues may come up if the default port of 8080 is already in use.

**Comment by chadbailey59** [comment]
Got it. I had sort-of figured that out yesterday, but was hoping I wouldn't have to log in each time. That seriously hampers the usability for me. :(

**Comment by brschwar** [comment]
Agreed! At least if that is how it worked originally, we wouldn't have gotten spoiled! Glad you were able to get it working. It's still pretty useful to use and develop completely in the browser at times.

**Comment by Taghavi83** [comment]
Please help!
I followed the instructions, and I can't make it seem to work. 

-I installed the extension. 
-On my terminal I wrote: npm install -g devtools-terminal

And I get the following error:
> pty.js@0.2.13 install /usr/local/lib/node_modules/devtools-terminal/node_modules/pty.js
> node-gyp rebuild

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/devtools-terminal/node_modules/pty.js
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
|
> ws@0.4.32 install /usr/local/lib/node_modules/devtools-terminal/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "devtools-terminal"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alextaghavi/npm-debug.log
Alexs-MacBook-Pro:~ alextaghavi$ npm install -g /tmp/pty.js
npm ERR! addLocal Could not install /tmp/pty.js
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "/tmp/pty.js"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /tmp/pty.js
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, open '/tmp/pty.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alextaghavi/npm-debug.log

**Comment by Fabs** [comment]
I followed what @fungl164  said, and it did not worked. I still have the same problem as @brschwar. I was able to install normally anyway. 

 devtools-terminal
   info  - socket.io started

I have Chrome Version 48.0.2564.79 beta (64-bit)
