### ISSUE TITLE
install didn't work issue after installing nodejs

### ISSUE THREAD

**Issue by foxsan48** [petethepig/devtools-terminal#61]
sudo npm install -g devtools-terminal

> pty.js@0.2.7 install /usr/local/lib/node_modules/devtools-terminal/node_modules/pty.js
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/redis/0.7.3
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/devtools-terminal/node_modules/pty.js
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm http 200 https://registry.npmjs.org/socket.io-client/-/socket.io-client-0.9.16.tgz
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by osvalr** [comment]
confirming this
