### ISSUE TITLE
NPM install fail

### ISSUE THREAD

**Issue by marocas** [petethepig/devtools-terminal#64]
````javascript
Last login: Mon Jul 13 14:14:34 on ttys000
Marocas:bystarter mariosilva$ npm install -g devtools-terminal
 
> pty.js@0.2.8 install /usr/local/lib/node_modules/devtools-terminal/node_modules/pty.js
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:72:28)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Darwin 12.6.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/devtools-terminal/node_modules/pty.js
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> ws@0.4.32 install /usr/local/lib/node_modules/devtools-terminal/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm ERR! Darwin 12.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "devtools-terminal"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mariosilva/Sites/bystarter/npm-debug.log
````

**Comment by petethepig** [comment]
@marocas Pay attention to this part:
```shell
npm ERR! Failed at the pty.js@0.2.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
```

**Comment by marocas** [comment]
Thanks m8.
