### ISSUE TITLE
module.js:440   return process.dlopen(module, path._makeLong(filename));

### ISSUE THREAD

**Issue by AlexLuya** [petethepig/devtools-terminal#70]
Hello,
      I am using ubuntu14.04 with nodejs v5.10.1,when run:
````bash
sudo devtools-terminal --install --id=leakmhneaibbdapdoienlkifomjceknl
````
got:
````bash
module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/devtools-terminal/node_modules/pty.js/lib/pty.js:9:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
````
 and after googling,it tells me install:nodejs-leagcy can fix this problem,but
````bash
sudo apt-get install nodejs-legacy 
````
gives me:
````bash
 nodejs-legacy : Depends: nodejs (>= 0.6.19~dfsg1-3~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
````
So,how to solve this problem?

**Comment by photous** [comment]
I have this issue too.

Even after installing `nodejs-legacy`

**Comment by AlexLuya** [comment]
After removing nodejs-5.x ppa,then purging nodejs,nodejs-legacy can be installed,and then others worked
