### ISSUE TITLE
sudo devtools-terminal --install --id=leakmhneaibbdapdoienlkifomjceknl Error

### ISSUE THREAD

**Issue by BrendanVgithub** [petethepig/devtools-terminal#72]
use "sudo devtools-terminal --install --id=leakmhneaibbdapdoienlkifomjceknl" happen Error. 
OS:mac  10.11.5
chrome:  51.0.2704.63
Error information:

sudo devtools-terminal --install --id=leakmhneaibbdapdoienlkifomjceknl
module.js:341
    throw err;
    ^

Error: Cannot find module '../build/Release/pty.node'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/devtools-terminal/node_modules/pty.js/lib/pty.js:9:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

**Comment by fidoChou** [comment]
I encountered the same problem, Can you tell me have you make it and how? :)
